/* JS-only snippet (paired with `deep_clone.js`).
 *
 * The C path's owned-value protocol (per-typedef `_copy` helpers
 * generated by `emitNamedTypedef`) provides the equivalent
 * always-copy semantics. This snippet exists only to give the
 * activation system a `.h` sibling for the JS-side
 * `mtoc2_deep_clone` helper; the C body is intentionally empty.
 */
