#!/usr/bin/env tsx
/**
 * Generate src/codegen/runtime/snippets.gen.ts by inlining every .h file
 * under src/codegen/runtime/ as a string literal. The codegen runtime
 * module imports from the generated file instead of reading the .h files
 * at runtime, which lets the translator bundle in the browser.
 *
 *   npx tsx scripts/build_runtime_snippets.ts          # write the file
 *   npx tsx scripts/build_runtime_snippets.ts --check  # exit 1 if drifted
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const runtimeDir = resolve(here, "..", "src", "codegen", "runtime");
const outFile = join(runtimeDir, "snippets.gen.ts");

function generate(): string {
  const files = readdirSync(runtimeDir)
    .filter(f => f.endsWith(".h"))
    .sort();
  const entries = files.map(f => {
    const body = readFileSync(join(runtimeDir, f), "utf8");
    return `  ${JSON.stringify(f)}: ${JSON.stringify(body)},`;
  });
  return [
    "// DO NOT EDIT — generated by scripts/build_runtime_snippets.ts.",
    "// Re-run `npm run build:snippets` after editing any runtime/*.h file.",
    "",
    "export const SNIPPETS: Record<string, string> = {",
    ...entries,
    "};",
    "",
  ].join("\n");
}

const generated = generate();
const check = process.argv.includes("--check");

if (check) {
  let current = "";
  try {
    current = readFileSync(outFile, "utf8");
  } catch {
    /* file missing counts as drift */
  }
  if (current !== generated) {
    console.error(
      "snippets.gen.ts is out of date. Run `npm run build:snippets`."
    );
    process.exit(1);
  }
  process.exit(0);
}

writeFileSync(outFile, generated);
console.log(`wrote ${outFile}`);
