#!/usr/bin/env tsx
/**
 * Generate src/codegen/runtime/snippets.gen.ts by inlining every .h
 * and .js file under src/codegen/runtime/ as a string literal. The
 * codegen runtime module imports from the generated file instead of
 * reading the source files at runtime, which lets the translator
 * bundle in the browser.
 *
 * Pairing: a `disp_double.h` may be paired with an optional
 * `disp_double.js` (same basename). The C side is the primary
 * registration; the JS side is auxiliary, consumed by `emitJs`. A
 * snippet that has no `.js` sibling falls back to "no JS emit
 * support" — see `RuntimeSnippet.jsCode` in `runtime.ts`.
 *
 * .js snippet contract:
 *   - A valid standalone ES module (so the interpreter side can
 *     `import { foo } from "./snippets.gen.js"`).
 *   - No `import` statements between snippet files (each snippet is
 *     self-contained; cross-snippet calls resolve via module scope
 *     once the codegen inlines them all into one emitted module).
 *   - References host hooks (e.g. `$write`) as free variables, which
 *     resolve to `globalThis.<name>` at call time. The host assigns
 *     them before any snippet runs.
 *   - Top-level names must not collide across snippet files.
 *
 *   npx tsx scripts/build_runtime_snippets.ts          # write the file
 *   npx tsx scripts/build_runtime_snippets.ts --check  # exit 1 if drifted
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const runtimeDir = resolve(here, "..", "src", "builtins", "runtime");
const outFile = join(runtimeDir, "snippets.gen.ts");

function stripJsExportsAndImports(src: string): string {
  // Remove `export ` from top-level function/const/let/class declarations.
  // The inlined codegen text needs plain declarations so the surrounding
  // emitted module can reference them by bare name.
  let out = src.replace(/^export\s+(function|const|let|class)\b/gm, "$1");
  // Drop `import { ... } from "./<sibling>.js";` lines. Sibling
  // imports are kept in the source files so the *interpreter* can
  // load snippets as real ES modules; for codegen all snippets get
  // inlined into one emitted module, so cross-snippet calls resolve
  // via module scope and the imports become redundant.
  out = out.replace(/^\s*import\s+.*?from\s+["'][^"']+["'];?\s*$/gm, "");
  return out;
}

function assertImportsAreSiblings(src: string, file: string): void {
  const matches = src.matchAll(/^\s*import\s+.*?from\s+["']([^"']+)["']/gm);
  for (const m of matches) {
    const spec = m[1];
    // Accept only relative same-directory imports referring to another
    // `.js` snippet — the interpreter resolves these via real ESM, and
    // the codegen path strips them and inlines all snippets together.
    if (!/^\.\/[A-Za-z0-9_]+\.js$/.test(spec)) {
      throw new Error(
        `${file}: snippet 'import' must reference a sibling snippet ` +
          `via "./<name>.js"; got "${spec}".`
      );
    }
  }
}

function generate(): string {
  const allFiles = readdirSync(runtimeDir)
    .filter(f => f !== "snippets.gen.ts")
    .sort();

  const hFiles = allFiles.filter(f => f.endsWith(".h"));
  const jsFiles = allFiles.filter(f => f.endsWith(".js"));
  const dtsFiles = allFiles.filter(f => f.endsWith(".d.ts"));
  void dtsFiles; // ambient .d.ts files are typecheck-only; not inlined

  const cEntries = hFiles.map(f => {
    const body = readFileSync(join(runtimeDir, f), "utf8");
    return `  ${JSON.stringify(f)}: ${JSON.stringify(body)},`;
  });

  const jsEntries = jsFiles.map(f => {
    const body = readFileSync(join(runtimeDir, f), "utf8");
    assertImportsAreSiblings(body, f);
    const stripped = stripJsExportsAndImports(body);
    return `  ${JSON.stringify(f)}: ${JSON.stringify(stripped)},`;
  });

  // Re-export every named export from each .js snippet so the
  // interpreter (Phase 3) can `import { foo } from
  // "./snippets.gen.js"` and call helpers directly — same source of
  // truth the emitter inlines.
  const reExports = jsFiles
    .map(f => `export * from ${JSON.stringify("./" + f)};`)
    .join("\n");

  return [
    "// DO NOT EDIT — generated by scripts/build_runtime_snippets.ts.",
    "// Re-run `npm run build:snippets` after editing any runtime/*.h",
    "// or runtime/*.js file.",
    "",
    "// Re-exports of every named export from each .js snippet, so the",
    "// interpreter / `Builtin.call` definitions can import helpers",
    "// directly and run the same code the emitters inline.",
    reExports,
    "",
    "/** C snippet bodies, keyed by filename (e.g. `disp_double.h`). */",
    "export const C_SNIPPETS: Record<string, string> = {",
    ...cEntries,
    "};",
    "",
    "/** JS snippet bodies (with `export` keywords stripped), keyed by",
    " *  filename (e.g. `disp_double.js`). Inlined into emitted JS. The",
    " *  functions may reference host hooks (`$write`, …) as free",
    " *  variables that resolve to `globalThis.<name>` at call time. */",
    "export const JS_SNIPPETS: Record<string, string> = {",
    ...jsEntries,
    "};",
    "",
  ].join("\n");
}

const generated = generate();
const check = process.argv.includes("--check");

if (check) {
  let current = "";
  try {
    current = readFileSync(outFile, "utf8");
  } catch {
    /* file missing counts as drift */
  }
  if (current !== generated) {
    console.error(
      "snippets.gen.ts is out of date. Run `npm run build:snippets`."
    );
    process.exit(1);
  }
  process.exit(0);
}

writeFileSync(outFile, generated);
console.log(`wrote ${outFile}`);
